# NumPy Indexing and Selection


In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[2:5]

array([2, 3, 4])

In [7]:
arr[:5], arr[5:]

(array([0, 1, 2, 3, 4]), array([ 5,  6,  7,  8,  9, 10]))

In [8]:
arr = np.arange(0,11)
arr_slice = arr[0:6]
print(arr_slice)
arr_slice[:] = 99
print(arr_slice)
print(arr)

[0 1 2 3 4 5]
[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]


In [14]:
arr = np.arange(0,11)
arr_slice = arr[0:6].copy()
print(arr_slice)
arr_slice[:] = 99
print(arr_slice)
print(arr)


[0 1 2 3 4 5]
[99 99 99 99 99 99]
[ 0  1  2  3  4  5  6  7  8  9 10]


### 2d array indexing

In [20]:
list_2d = [[5,10,15], [20,25,30], [35,40,45]]
arr_2d = np.array(list_2d)
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
arr_2d[0,0], arr_2d[0][1]

(5, 10)

In [24]:
arr_2d[2,1], arr_2d[1][1]

(40, 25)

In [30]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [32]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [31]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [33]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [36]:
# conditional selection
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [42]:
arr[bool_arr]


array([ 6,  7,  8,  9, 10])

In [43]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [46]:
arr[arr<=3]

array([1, 2, 3])

In [48]:
# create a new 2d array
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [54]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [56]:
arr_2d = np.arange(100).reshape(10,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [57]:
arr_2d[4:6,4:6]

array([[44, 45],
       [54, 55]])