In [9]:
import numpy as np

# 1 d array is called vectors
# multi dimensional array is called matrices
# py = python
# npy = numpy

py_arr = [1,2,3]
npy_arr = np.array(py_arr)

py_mat = [[1,2,3],[4,5,6], [7,8,9]]
npy_mat = np.array(py_mat)

In [12]:
np.arange(0,10)



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.zeros((2,4)) # args rows, col


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((7,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
# use shift + tab to view documentation
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [15]:
np.eye(4) # identity Matrices

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand(5) # random matrices

array([0.92372799, 0.43586629, 0.0722547 , 0.89654147, 0.09351001])

In [25]:
np.random.rand(5,5) # random matrices

array([[0.09002516, 0.63870457, 0.2817122 , 0.16719388, 0.3846849 ],
       [0.93756599, 0.4353096 , 0.10926519, 0.68645326, 0.66398599],
       [0.79672214, 0.82981152, 0.75884056, 0.71347445, 0.78996981],
       [0.56249948, 0.02348991, 0.59737712, 0.61364005, 0.55544232],
       [0.57868404, 0.60345308, 0.05255388, 0.31058535, 0.5203464 ]])

In [19]:
np.random.randn(4,4) # random matrices standard deistribution

array([[ 0.6671812 , -0.98768985,  2.046153  , -0.56689004],
       [-0.13547976,  0.9905695 ,  0.3422871 , -0.13274601],
       [ 1.77838481,  0.01532279, -0.16922377,  2.12191317],
       [ 1.05596481,  0.88963338,  0.03601692, -0.72993007]])

In [28]:
np.random.randint(1,100)

27

In [29]:
np.random.randint(1,100,10)

array([35,  9, 20, 27, 42, 81, 57, 95, 12, 40])

In [31]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
ranarr = np.random.randint(0,25,10)
ranarr

array([19,  6,  9, 12, 20,  8, 24,  5, 14,  8])

In [52]:
arr.reshape(5,5) # changing 1d to 2d by passing row , col

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
ranarr.max(), ranarr.min()

(24, 5)

In [62]:
 ranarr.argmax(), ranarr.argmin() # get the index of min/max elements

(6, 7)

In [66]:
ranarr.shape

(10,)